name: Composer and test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: pecl

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Download GeoIP database
      run: curl "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ secrets.MAXMIND_API_KEY }}&suffix=tar.gz" --output /tmp/geo.tar.gz
      
    - name: Extract GeoIP database
      run: cd /tmp/; tar zxvf geo.tar.gz; mv GeoLite2-Country*/GeoLite2-Country.mmdb . 

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: ./vendor/bin/phpunit tests/
      env:
          vatlayer_api_key: ${{ secrets.VATLAYER_API_KEY }}
          hmrc_use_live_api: false
          geoip_db_path: /tmp/GeoLite2-Country.mmdb
